### ISSUE TITLE
imapsync.pl is broken and UI doesn't work

### ISSUE THREAD

**Issue by zietbukuel** [server-gurus/RCimapSync#11]
I've tried configuring the plugin according to the documentation but I cannot make it work. First, the UI won't even work, it's not present in the system. I've enabled the plugin and followed every step. I'm running it with RC 1.3.9 in Ubuntu 18.04.

The imapsync.pl script is also broken. First it cannot run it because of the following errors:

`Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /var/www/webmail/public/plugins/rcimapsync/bin/imapsync.pl line 4.
BEGIN failed--compilation aborted at /var/www/webmail/public/plugins/rcimapsync/bin/imapsync.pl line 4`

And I'm pretty sure I have installed that library.

I also get this error:

`Can't locate config.conf in @INC (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /var/www/webmail/public/plugins/rcimapsync/bin/imapsync.pl line 15.
WARNING: releasing 1 pending lock...`

After changing this line:

`require "config.conf" || log_and_die($!);`

To

`require "./config.conf" || log_and_die($!);`

I get this error:

`install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 9) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Proxy, Sponge.
 at /var/www/webmail/public/plugins/rcimapsync/bin/imapsync.pl line 17.
WARNING: releasing 1 pending lock...`

It's a complete mess. Help please?

**Comment by nelgin** [comment]
Looks like you don't have the DBI perl modules installed. I don't use Ubuntu day-to-day but I think you need libdbi-perl or something like that.

**Comment by zietbukuel** [comment]
I had it installed, but for some reason, it couldn't find it. Anyways, this is an old ticket, closing.
