### ISSUE TITLE
servergurus/rcimapsync 1.1.0 requires imapsync >=1.7

### ISSUE THREAD

**Issue by internethering** [server-gurus/RCimapSync#2]
Hi, 

I added you plugin to my roundcubes composer.json and the update fails:

>   Problem 1
>     - Installation request for servergurus/rcimapsync ~1.1.0 -> satisfiable by servergurus/rcimapsync[1.1.0].
>     - servergurus/rcimapsync 1.1.0 requires imapsync >=1.7 -> no matching package found.

Please remove this requirement.

**Comment by DaCHRIS** [comment]
Hi, just removed that requirement. 

Can you test if it works now?
